language: ruby
script: ./script/cibuild
before_install:
  - ./script/bootstrap
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.6.5
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  allow_failures:
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"